---
title: "About"
---
As a dedicated Computer Sciences and Engineering graduate with a passion for leveraging data-driven insights, I am excited to embark on a journey to explore the dynamic field of data science. With a solid foundation in programming languages such as Python, Java, and SQL, I am eager to expand my skill set and pursue further education in statistical modeling, predictive analytics, and data visualization.

Driven by a desire to solve real-world problems, I am particularly interested in applying data-driven approaches, including natural language processing, computer vision, and recommendation systems. I am committed to continuous learning and staying abreast of the latest advancements in the field.

If you are seeking a motivated and adaptable professional with a strong background in computer sciences and a future focus on Data Science/Analytics or Business Analytics , let's connect. I am open to new opportunities and look forward to contributing my skills to projects that make a positive impact.
